// Search-facing and buying-guide copy. Specifications remain in js/products.js.
export const seoCopy = {
  'zh-TW': {
    'meta.title': '佰客 Beky 折疊車｜青春・天際 Skyline・NANO',
    'meta.desc': '探索佰客 Beky 折疊車：青春 16 吋、天際 Skyline 18 吋寬胎、NANO 14 吋。查看車款規格、配色與選車比較，透過官方 LINE 詢問購買方式，找到適合城市通勤與日常收納的小折。',
    'hero.sub': '佰客 Beky 折疊車，讓城市保有剛剛好的距離。',
    'sec.products': '佰客折疊車系列',
    'products.intro': '青春 16 吋、天際 18 吋寬胎、NANO 14 吋。從日常騎乘到折疊收納，找一台合拍的小折。',
    'p.youth.name': '青春 16 吋折疊車', 'p.skyline.name': '天際 Skyline 18 吋寬胎折疊車', 'p.nano.name': 'NANO 14 吋折疊車',
    'compare.title': '青春、天際、NANO，怎麼選？',
    'compare.lead': '先想想每天怎麼騎、回家放哪裡，再比較輪徑與變速配置。',
    'compare.youth': '想從日常短程騎乘開始，可以先看看 16 吋青春。6 速配置，作為認識佰客折疊車的起點。',
    'compare.skyline': '偏好寬胎配置，可以看看天際 Skyline。18 × 2.125 輪胎與 7 速變速，是三款之中不同的選擇。',
    'compare.nano': '在意折疊後的收納空間，可以先看看 14 吋 NANO。小輪徑搭配 4 速配置，再依實際需求確認是否合適。',
    'compare.note': '選購前，請確認所選版本的重量、折疊尺寸、車色與交期；若需要搬上樓或收進車廂，建議先量好空間。',
    'compare.view': '查看完整規格與配色', 'pd.enquire': '詢問車款與購買方式', 'pd.price.tba': '請透過官方 LINE 詢問',
    'news.community': '社團最新動態', 'nav.stores': '購車與經銷諮詢',
    'store.1.name': '購車與車款諮詢', 'store.1.addr': '請透過 Beky 官方 LINE 詢問車款、配色與購買方式。', 'store.hours': '購買前，請先確認交期與交車安排。',
    'store.2.name': '經銷與展示合作', 'store.2.addr': '歡迎透過官方 LINE 洽談合作。', 'store.2.cta': '聯絡 Beky',
    'f.shop.2': '購買與交車諮詢', 'f.shop.3': '其他問題諮詢',
    'f.support.1': '維修保養諮詢', 'f.support.2': '保固內容諮詢', 'f.support.3': '折疊操作諮詢',
  },
  en: {
    'meta.title': 'Beky Folding Bikes | Youth, Skyline & NANO',
    'meta.desc': 'Explore Beky folding bikes: 16-inch Youth, 18-inch wide-tyre Skyline and 14-inch NANO. Compare specifications and colours, then contact Beky on LINE for purchasing information.',
    'hero.sub': 'Beky folding bikes keep the city at just the right distance.',
    'sec.products': 'Beky Folding Bikes',
    'products.intro': '16-inch Youth, 18-inch wide-tyre Skyline and 14-inch NANO. Find a folding bike that fits your daily rides and storage space.',
    'p.youth.name': 'Youth 16-inch Folding Bike', 'p.skyline.name': 'Skyline 18-inch Wide-tyre Folding Bike', 'p.nano.name': 'NANO 14-inch Folding Bike',
    'compare.title': 'Youth, Skyline or NANO?',
    'compare.lead': 'Start with your daily rides and where you will store the bike, then compare wheel sizes and gearing.',
    'compare.youth': 'For everyday short rides, start by exploring the 16-inch Youth. Its 6-speed setup offers a starting point for getting to know Beky folding bikes.',
    'compare.skyline': 'If you prefer a wide-tyre setup, explore Skyline. Its 18 × 2.125 tyres and 7-speed drivetrain offer a different configuration within this trio.',
    'compare.nano': 'If folded storage space matters most, take a look at the 14-inch NANO. Check whether its smaller wheels and 4-speed setup suit your needs.',
    'compare.note': 'Before ordering, confirm the weight, folded dimensions, colour and lead time of your chosen version. Measure your storage space if you plan to carry it upstairs or place it in a car.',
    'compare.view': 'View specifications and colours', 'pd.enquire': 'Ask about this bike and how to buy', 'pd.price.tba': 'Please ask Beky on LINE',
    'news.community': 'Community updates', 'nav.stores': 'Buying & dealer enquiries',
    'store.1.name': 'Bike & purchase enquiries', 'store.1.addr': 'Contact Beky on LINE to ask about models, colours and how to buy.', 'store.hours': 'Please confirm lead time and handover arrangements before ordering.',
    'store.2.name': 'Dealer & display partnerships', 'store.2.addr': 'Contact Beky on LINE to discuss working together.', 'store.2.cta': 'Contact Beky',
    'f.shop.2': 'Purchase & handover enquiries', 'f.shop.3': 'Other questions',
    'f.support.1': 'Maintenance enquiries', 'f.support.2': 'Warranty enquiries', 'f.support.3': 'Folding enquiries',
  },
  'zh-CN': {
    'meta.title': '佰客 Beky 折叠车｜青春・天际 Skyline・NANO',
    'meta.desc': '探索佰客 Beky 折叠车：青春 16 英寸、天际 Skyline 18 英寸宽胎、NANO 14 英寸。查看车型规格、配色与选车比较，通过官方 LINE 咨询购买方式，找到适合城市通勤与日常收纳的小折。',
    'hero.sub': '佰客 Beky 折叠车，让城市保有刚刚好的距离。',
    'sec.products': '佰客折叠车系列',
    'products.intro': '青春 16 英寸、天际 18 英寸宽胎、NANO 14 英寸。从日常骑行到折叠收纳，找一台合拍的小折。',
    'p.youth.name': '青春 16 英寸折叠车', 'p.skyline.name': '天际 Skyline 18 英寸宽胎折叠车', 'p.nano.name': 'NANO 14 英寸折叠车',
    'compare.title': '青春、天际、NANO，怎么选？',
    'compare.lead': '先想想每天怎么骑、回家放哪里，再比较轮径与变速配置。',
    'compare.youth': '想从日常短程骑行开始，可以先看看 16 英寸青春。6 速配置，作为认识佰客折叠车的起点。',
    'compare.skyline': '偏好宽胎配置，可以看看天际 Skyline。18 × 2.125 轮胎与 7 速变速，是三款之中不同的选择。',
    'compare.nano': '在意折叠后的收纳空间，可以先看看 14 英寸 NANO。小轮径搭配 4 速配置，再依实际需求确认是否合适。',
    'compare.note': '选购前，请确认所选版本的重量、折叠尺寸、车色与交期；若需要搬上楼或收进后备箱，建议先量好空间。',
    'compare.view': '查看完整规格与配色', 'pd.enquire': '咨询车型与购买方式', 'pd.price.tba': '请通过官方 LINE 咨询',
    'news.community': '社群最新动态', 'nav.stores': '购车与经销咨询',
    'store.1.name': '购车与车型咨询', 'store.1.addr': '请通过 Beky 官方 LINE 咨询车型、配色与购买方式。', 'store.hours': '购买前，请先确认交期与交车安排。',
    'store.2.name': '经销与展示合作', 'store.2.addr': '欢迎通过官方 LINE 洽谈合作。', 'store.2.cta': '联系 Beky',
    'f.shop.2': '购买与交车咨询', 'f.shop.3': '其他问题咨询',
    'f.support.1': '维修保养咨询', 'f.support.2': '保修内容咨询', 'f.support.3': '折叠操作咨询',
  },
  ja: {
    'meta.title': 'BEKY（佰客）折りたたみ自転車｜青春・SKYLINE・NANO',
    'meta.desc': 'BEKY（佰客）の折りたたみ自転車。16インチの青春、18インチのワイドタイヤモデルSKYLINE、14インチのNANOの仕様やカラーを比較できます。購入方法は公式LINEへお問い合わせください。',
    'hero.sub': 'BEKY（佰客）の折りたたみ自転車が、街との距離をちょうどよくしてくれます。',
    'sec.products': 'BEKYの折りたたみ自転車',
    'products.intro': '16インチの青春、18インチのワイドタイヤモデルSKYLINE、14インチのNANO。日々の移動と収納場所に合う一台を。',
    'p.youth.name': '青春 16インチ 折りたたみ自転車', 'p.skyline.name': 'SKYLINE 18インチ ワイドタイヤ 折りたたみ自転車', 'p.nano.name': 'NANO 14インチ 折りたたみ自転車',
    'compare.title': '青春・SKYLINE・NANOの選び方',
    'compare.lead': '毎日の走り方と収納場所を思い浮かべながら、ホイールサイズと変速段数を比べてみましょう。',
    'compare.youth': '日常の短距離移動から始めたい方は、16インチの青春を。6段変速を備え、BEKYの折りたたみ自転車を知るきっかけとなるモデルです。',
    'compare.skyline': 'ワイドタイヤをお探しならSKYLINEを。18 × 2.125のタイヤと7段変速を備えた、3モデルの中でも異なる仕様の一台です。',
    'compare.nano': '折りたたんだときの収納スペースを重視する方は、14インチのNANOを。小径ホイールと4段変速が使い方に合うか、ご確認ください。',
    'compare.note': 'ご購入前に、ご希望の仕様の重量・折りたたみサイズ・カラー・納期をご確認ください。階段での持ち運びや車載を予定している場合は、収納場所の寸法も確認しましょう。',
    'compare.view': '仕様とカラーを見る', 'pd.enquire': 'モデルと購入方法について問い合わせる', 'pd.price.tba': '公式LINEへお問い合わせください',
    'news.community': 'コミュニティのお知らせ', 'nav.stores': '購入・販売店のお問い合わせ',
    'store.1.name': 'モデル・購入について', 'store.1.addr': 'モデル、カラー、購入方法はBEKY公式LINEへお問い合わせください。', 'store.hours': 'ご購入前に納期と受け取り方法をご確認ください。',
    'store.2.name': '販売・展示パートナー募集', 'store.2.addr': '提携のご相談は公式LINEへお問い合わせください。', 'store.2.cta': 'BEKYに問い合わせる',
    'f.shop.2': '購入・受け取りのご相談', 'f.shop.3': 'その他のお問い合わせ',
    'f.support.1': 'メンテナンスのご相談', 'f.support.2': '保証内容のお問い合わせ', 'f.support.3': '折りたたみ操作のご相談',
  },
};
